name: .NET Continuous Deployment

on:
  push:
    branches: [ master ]
    paths:
      - src/**
  workflow_dispatch:
jobs:

  test:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Run tests
        run: dotnet test

  semantic-release:
    needs: test
    name: Create a Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Need the full commit history for conventional commit
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - name: Compile binary
        run: dotnet build -c Release ./src/MyApp/MyApp.csproj -p:Version=${{ steps.tag_version.outputs.new_version }} -o ./artifacts
      - name: Create github release and attach binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "/home/runner/work/test-repo/test-repo/artifacts/MyApp.dll"
          asset_name: "MyApp.dll"
          tag: ${{ steps.tag_version.outputs.new_version }}
          overwrite: true
          body: "Sample release."
